spring:
  application:
    name: tivo-demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: tivo-demo
message:
  basic-topic: user-basic
  message-topic: user-message
  detail-topic: user-detail
  messages-per-request: 10
  
logging:
  level:
    root: INFO
  
